In [4]:
import pandas as pd
df = pd.read_csv('/content/Vendasloja - Vendasloja.csv')
print(df)

               Produto       Categoria   Qtd    Preço       Cidade
0             Notebook     Eletrônicos   2.0   3500.0       Manaus
1                Mouse      Periférico   5.0     80.0       Manaus
2              Monitor     Eletrônicos   1.0   1200.0        Belém
3              Teclado      Periférico   3.0    150.0       Manaus
4           Impressora      Periférico   2.0    950.0       Manaus
5              Headset      Periférico   6.0    220.0    Boa Vista
6               Webcam      Periférico   4.0    320.0       Manaus
7            SSD 480GB   Armazenamento   8.0    350.0        Belém
8           HD Externo   Armazenamento   3.0    480.0       Manaus
9       Notebook Gamer     Eletrônicos   1.0   6200.0  Porto Velho
10         Mouse Gamer      Periférico   7.0    180.0    Boa Vista
11          Monitor 27     Eletrônicos   2.0   1800.0       Manaus
12       Cadeira Gamer          Móveis   1.0   1400.0        Belém
13     Mesa Escritório          Móveis   2.0    950.0       Manaus
14    Switch 24 Portas           Redes   1.0   1300.0   Rio Branco
15       Roteador WiFi           Redes   4.0    420.0       Manaus
16        Access Point           Redes   3.0    690.0    Boa Vista
17            Servidor  Infraestrutura   1.0  12500.0       Manaus
18             NoBreak  Infraestrutura   2.0   2100.0        Belém
19             Scanner      Periférico   2.0    850.0  Porto Velho
20            Projetor      Multimídia   1.0   2800.0       Manaus
21        Caixa de Som      Multimídia   5.0    390.0   Rio Branco
22            Notebook     Eletrônicos   2.0   3500.0       Manaus
23               Mouse      Periférico   5.0     80.0       Manaus
24    Teclado Mecânico      Periférico   3.0    420.0       Manaus
25  Notebook Ultrafino     Eletrônicos   1.0   5100.0    Boa Vista
26              Tablet     Eletrônicos   4.0   1800.0       Manaus
27          Smartphone     Eletrônicos   6.0   2400.0        Belém
28       Pendrive 64GB   Armazenamento  10.0     60.0       Manaus
29             SSD 1TB   Armazenamento   5.0    720.0   Rio Branco
30              HD 2TB   Armazenamento   3.0    590.0    Boa Vista
31   Monitor Ultrawide     Eletrônicos   1.0   2500.0       Manaus
32    Impressora Laser      Periférico   2.0   1600.0        Belém
33            Notebook             NaN   2.0   3500.0       Manaus
34               Mouse      Periférico   NaN     80.0       Manaus
35             Monitor     Eletrônicos   1.0      NaN        Belém
36             Teclado      Periférico   3.0    150.0          NaN
37    Switch 48 Portas           Redes   1.0   2600.0          NaN
38       Servidor Rack  Infraestrutura   NaN  15800.0       Manaus
39            Projetor      Multimídia   1.0      NaN    Boa Vista
40             Scanner      Periférico   NaN    850.0          NaN
41      Notebook Gamer     Eletrônicos   1.0   6200.0  Porto Velho
42              Webcam      Periférico   5.0    320.0       Manaus
43       Cadeira Gamer          Móveis   2.0   1400.0       Manaus
44     Mesa Escritório          Móveis   3.0    950.0    Boa Vista
45       Roteador WiFi           Redes   5.0    420.0        Belém
46        Access Point           Redes   2.0    690.0   Rio Branco
47           SSD 480GB   Armazenamento   6.0    350.0       Manaus
48             Headset      Periférico   4.0    220.0        Belém
49             NoBreak  Infraestrutura   1.0   2100.0       Manaus
50          Monitor 27     Eletrônicos   2.0   1800.0       Manaus
51          Monitor 27     Eletrônicos   2.0   1800.0       Manaus

In [5]:

df.head()   #mostrar as  1 linhas
df.tail()   #mostra as ultimas linhas
df.shape    #mostar tamanho da tabela
df.columns   #mostar nome das colunas
df.info()    #informacao da tabela,numero de linhas, colunas, qual tipo de dados

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Produto    52 non-null     object
 1   Categoria  51 non-null     object
 2   Qtd        49 non-null     float64
 3   Preço      50 non-null     float64
 4   Cidade     49 non-null     object
dtypes: float64(2), object(3)
memory usage: 2.2+ KB

In [6]:
# mostar as  1 linhas
df.head(10)
df.head(8)

      Produto      Categoria  Qtd   Preço     Cidade
0    Notebook    Eletrônicos  2.0  3500.0     Manaus
1       Mouse     Periférico  5.0    80.0     Manaus
2     Monitor    Eletrônicos  1.0  1200.0      Belém
3     Teclado     Periférico  3.0   150.0     Manaus
4  Impressora     Periférico  2.0   950.0     Manaus
5     Headset     Periférico  6.0   220.0  Boa Vista
6      Webcam     Periférico  4.0   320.0     Manaus
7   SSD 480GB  Armazenamento  8.0   350.0      Belém

In [7]:
df.sample(3)

         Produto    Categoria  Qtd   Preço      Cidade
11    Monitor 27  Eletrônicos  2.0  1800.0      Manaus
34         Mouse   Periférico  NaN    80.0      Manaus
46  Access Point        Redes  2.0   690.0  Rio Branco

In [8]:
#mostar colunas
df["Produto"]
df[["Produto", "Categoria"]]
df[["Produto", "Categoria","Preço"]]

               Produto       Categoria    Preço
0             Notebook     Eletrônicos   3500.0
1                Mouse      Periférico     80.0
2              Monitor     Eletrônicos   1200.0
3              Teclado      Periférico    150.0
4           Impressora      Periférico    950.0
5              Headset      Periférico    220.0
6               Webcam      Periférico    320.0
7            SSD 480GB   Armazenamento    350.0
8           HD Externo   Armazenamento    480.0
9       Notebook Gamer     Eletrônicos   6200.0
10         Mouse Gamer      Periférico    180.0
11          Monitor 27     Eletrônicos   1800.0
12       Cadeira Gamer          Móveis   1400.0
13     Mesa Escritório          Móveis    950.0
14    Switch 24 Portas           Redes   1300.0
15       Roteador WiFi           Redes    420.0
16        Access Point           Redes    690.0
17            Servidor  Infraestrutura  12500.0
18             NoBreak  Infraestrutura   2100.0
19             Scanner      Periférico    850.0
20            Projetor      Multimídia   2800.0
21        Caixa de Som      Multimídia    390.0
22            Notebook     Eletrônicos   3500.0
23               Mouse      Periférico     80.0
24    Teclado Mecânico      Periférico    420.0
25  Notebook Ultrafino     Eletrônicos   5100.0
26              Tablet     Eletrônicos   1800.0
27          Smartphone     Eletrônicos   2400.0
28       Pendrive 64GB   Armazenamento     60.0
29             SSD 1TB   Armazenamento    720.0
30              HD 2TB   Armazenamento    590.0
31   Monitor Ultrawide     Eletrônicos   2500.0
32    Impressora Laser      Periférico   1600.0
33            Notebook             NaN   3500.0
34               Mouse      Periférico     80.0
35             Monitor     Eletrônicos      NaN
36             Teclado      Periférico    150.0
37    Switch 48 Portas           Redes   2600.0
38       Servidor Rack  Infraestrutura  15800.0
39            Projetor      Multimídia      NaN
40             Scanner      Periférico    850.0
41      Notebook Gamer     Eletrônicos   6200.0
42              Webcam      Periférico    320.0
43       Cadeira Gamer          Móveis   1400.0
44     Mesa Escritório          Móveis    950.0
45       Roteador WiFi           Redes    420.0
46        Access Point           Redes    690.0
47           SSD 480GB   Armazenamento    350.0
48             Headset      Periférico    220.0
49             NoBreak  Infraestrutura   2100.0
50          Monitor 27     Eletrônicos   1800.0
51          Monitor 27     Eletrônicos   1800.0

In [9]:
#FILTRANDO DADOS

df["Preço"] > 1000

0      True
1     False
2      True
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11     True
12     True
13    False
14     True
15    False
16    False
17     True
18     True
19    False
20     True
21    False
22     True
23    False
24    False
25     True
26     True
27     True
28    False
29    False
30    False
31     True
32     True
33     True
34    False
35    False
36    False
37     True
38     True
39    False
40    False
41     True
42    False
43     True
44    False
45    False
46    False
47    False
48    False
49     True
50     True
51     True
Name: Preço, dtype: bool

In [10]:
#Valores ausentes

df.isna()

    Produto  Categoria    Qtd  Preço  Cidade
0     False      False  False  False   False
1     False      False  False  False   False
2     False      False  False  False   False
3     False      False  False  False   False
4     False      False  False  False   False
5     False      False  False  False   False
6     False      False  False  False   False
7     False      False  False  False   False
8     False      False  False  False   False
9     False      False  False  False   False
10    False      False  False  False   False
11    False      False  False  False   False
12    False      False  False  False   False
13    False      False  False  False   False
14    False      False  False  False   False
15    False      False  False  False   False
16    False      False  False  False   False
17    False      False  False  False   False
18    False      False  False  False   False
19    False      False  False  False   False
20    False      False  False  False   False
21    False      False  False  False   False
22    False      False  False  False   False
23    False      False  False  False   False
24    False      False  False  False   False
25    False      False  False  False   False
26    False      False  False  False   False
27    False      False  False  False   False
28    False      False  False  False   False
29    False      False  False  False   False
30    False      False  False  False   False
31    False      False  False  False   False
32    False      False  False  False   False
33    False       True  False  False   False
34    False      False   True  False   False
35    False      False  False   True   False
36    False      False  False  False    True
37    False      False  False  False    True
38    False      False   True  False   False
39    False      False  False   True   False
40    False      False   True  False    True
41    False      False  False  False   False
42    False      False  False  False   False
43    False      False  False  False   False
44    False      False  False  False   False
45    False      False  False  False   False
46    False      False  False  False   False
47    False      False  False  False   False
48    False      False  False  False   False
49    False      False  False  False   False
50    False      False  False  False   False
51    False      False  False  False   False

In [11]:
#conta valor ausentes

df.isna().sum()

Produto      0
Categoria    1
Qtd          3
Preço        2
Cidade       3
dtype: int64

In [18]:
#tratar valores ausentes

df["Preço"] = df["Preço"].fillna(0)

In [22]:
#valores duplicados

df.duplicated().sum()

np.int64(0)

In [23]:
#removendo dados duplicados

df = df.drop_duplicates()

In [25]:
#criar coluna total
df["Total de vendas"] = df["Qtd"] * df["Preço"]

total_geral_vendas = df["Total de vendas"].sum()
print(f"Total Geral das Vendas: {total_geral_vendas:.2f}")

media_vendas = df["Total de vendas"].mean()
print(f"Média das Vendas: {media_vendas:.2f}")


maior_venda = df["Total de vendas"].max()
print(f"Maior Venda: {maior_venda:.2f}")


menor_venda = df["Total de vendas"].min()
print(f"Menor Venda: {menor_venda:.2f}")

Total Geral das Vendas: 125840.00
Média das Vendas: 2860.00
Maior Venda: 14400.00
Menor Venda: 0.00

In [26]:

#agrupar os dados

print('Total vendido por categoria:')
print(df.groupby('Categoria')['Total de vendas'].sum())

print('\nPreço médio por categoria:')
print(df.groupby('Categoria')['Preço'].mean())

print('\nQuantidade média por categoria:')
print(df.groupby('Categoria')['Qtd'].mean())

Total vendido por categoria:
Categoria
Armazenamento     12310.0
Eletrônicos       47200.0
Infraestrutura    18800.0
Multimídia         4750.0
Móveis             8950.0
Periférico        15700.0
Redes             11130.0
Name: Total de vendas, dtype: float64

Preço médio por categoria:
Categoria
Armazenamento      425.000000
Eletrônicos       2722.222222
Infraestrutura    8125.000000
Multimídia        1063.333333
Móveis            1175.000000
Periférico         456.428571
Redes             1020.000000
Name: Preço, dtype: float64

Quantidade média por categoria:
Categoria
Armazenamento     5.833333
Eletrônicos       2.111111
Infraestrutura    1.333333
Multimídia        2.333333
Móveis            2.000000
Periférico        3.833333
Redes             2.666667
Name: Qtd, dtype: float64

In [ ]:
#Estatísticas




df["Preço"].max() #maior valor
df["Preço"].min()  #menor valor


df["Preço"].sum()  #soma

np.float64(96830.0)

In [ ]:
df["Preço"].mean()  #média

np.float64(1936.6)

In [ ]:
df["Preço"].max() #maior valor

15800.0

In [ ]:
df["Preço"].min()  #menor valor

60.0

In [ ]:
df["Preço"].sum()  #soma

np.float64(96830.0)

In [ ]:
#ordenar dados

df.sort_values("Preço") #ordem crescente
df.sort_values("Preço", ascending=False)

               Produto       Categoria   Qtd    Preço       Cidade
38       Servidor Rack  Infraestrutura   NaN  15800.0       Manaus
17            Servidor  Infraestrutura   1.0  12500.0       Manaus
41      Notebook Gamer     Eletrônicos   1.0   6200.0  Porto Velho
9       Notebook Gamer     Eletrônicos   1.0   6200.0  Porto Velho
25  Notebook Ultrafino     Eletrônicos   1.0   5100.0    Boa Vista
0             Notebook     Eletrônicos   2.0   3500.0       Manaus
22            Notebook     Eletrônicos   2.0   3500.0       Manaus
33            Notebook             NaN   2.0   3500.0       Manaus
20            Projetor      Multimídia   1.0   2800.0       Manaus
37    Switch 48 Portas           Redes   1.0   2600.0          NaN
31   Monitor Ultrawide     Eletrônicos   1.0   2500.0       Manaus
27          Smartphone     Eletrônicos   6.0   2400.0        Belém
49             NoBreak  Infraestrutura   1.0   2100.0       Manaus
18             NoBreak  Infraestrutura   2.0   2100.0        Belém
50          Monitor 27     Eletrônicos   2.0   1800.0       Manaus
11          Monitor 27     Eletrônicos   2.0   1800.0       Manaus
26              Tablet     Eletrônicos   4.0   1800.0       Manaus
51          Monitor 27     Eletrônicos   2.0   1800.0       Manaus
32    Impressora Laser      Periférico   2.0   1600.0        Belém
12       Cadeira Gamer          Móveis   1.0   1400.0        Belém
43       Cadeira Gamer          Móveis   2.0   1400.0       Manaus
14    Switch 24 Portas           Redes   1.0   1300.0   Rio Branco
2              Monitor     Eletrônicos   1.0   1200.0        Belém
44     Mesa Escritório          Móveis   3.0    950.0    Boa Vista
4           Impressora      Periférico   2.0    950.0       Manaus
13     Mesa Escritório          Móveis   2.0    950.0       Manaus
19             Scanner      Periférico   2.0    850.0  Porto Velho
40             Scanner      Periférico   NaN    850.0          NaN
29             SSD 1TB   Armazenamento   5.0    720.0   Rio Branco
16        Access Point           Redes   3.0    690.0    Boa Vista
46        Access Point           Redes   2.0    690.0   Rio Branco
30              HD 2TB   Armazenamento   3.0    590.0    Boa Vista
8           HD Externo   Armazenamento   3.0    480.0       Manaus
15       Roteador WiFi           Redes   4.0    420.0       Manaus
45       Roteador WiFi           Redes   5.0    420.0        Belém
24    Teclado Mecânico      Periférico   3.0    420.0       Manaus
21        Caixa de Som      Multimídia   5.0    390.0   Rio Branco
47           SSD 480GB   Armazenamento   6.0    350.0       Manaus
7            SSD 480GB   Armazenamento   8.0    350.0        Belém
6               Webcam      Periférico   4.0    320.0       Manaus
42              Webcam      Periférico   5.0    320.0       Manaus
5              Headset      Periférico   6.0    220.0    Boa Vista
48             Headset      Periférico   4.0    220.0        Belém
10         Mouse Gamer      Periférico   7.0    180.0    Boa Vista
36             Teclado      Periférico   3.0    150.0          NaN
3              Teclado      Periférico   3.0    150.0       Manaus
1                Mouse      Periférico   5.0     80.0       Manaus
23               Mouse      Periférico   5.0     80.0       Manaus
34               Mouse      Periférico   NaN     80.0       Manaus
28       Pendrive 64GB   Armazenamento  10.0     60.0       Manaus
35             Monitor     Eletrônicos   1.0      NaN        Belém
39            Projetor      Multimídia   1.0      NaN    Boa Vista

In [27]:
#criar nova coluna

df["Desconto"] = df["Preço"] * 0.10

In [30]:
#salvando as alterações
df.to_csv("Vendasloja_novo.csv", index=False)